config/routes.rb
Rails.application.routes.draw do
  root 'album#home'
  get 'about' => 'album#about'
  get 'contact' => 'album#contact'
  get 'clients' => 'album#clients'
  get 'blog' => 'album#blog'

end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def blog
  end

  def clients
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	#Returns the full title on a per-page basis
	def full_title(page_title= '')
		base_title = "Palmetto Studios"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
			
		end
	end

end

app/views/album/about.html.erb
<%= provide(:title, "About")%>
<div class="content-row top-row">
	<div class="col-xs-12">
		<h2 id ="about"><i class="glyphicon glyphicon-camera glyphy"></i> About Palmetto Studios</h2>
	</div>
	<div class="carousel slide top-row col-lg-6 col-md-6 col-xs-12" id="my-carousel">
	  	<ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		    <li data-target="#myCarousel" data-slide-to="3"></li>  
	  	</ol>
			<div class="carousel-inner">
				<div class="item active">
					<%= image_tag "boyet5.jpg", :class=>"img img-responsive contact-logo" %>
					<span class="carousel-caption"><h4>Boyet Fidelino - Owner</h4></span>
				</div>
				<div class="item">
					<%= image_tag "boyet2.jpg", :class=>"img img-responsive contact-logo" %>
					<span class="carousel-caption"><h4>Boyet and his wife, Agnes</h4></span>
				</div>
				<div class="item">
					<%= image_tag "boyet3.jpg", :class=>"img img-responsive contact-logo" %>
					<span class="carousel-caption"><h4>The nature lover</h4></span>
				</div>
				<div class="item">
					<%= image_tag "boyet4.jpg", :class=>"img img-responsive contact-logo" %>
					<span class="carousel-caption"><h4>The Frequent Traveller</h4></span>
				</div>
			</div>
		<a href="#my-carousel" class="carousel-control left" data-slide="prev"><h2><i class="glyphicon glyphicon-chevron-left glyphy"></i></a>
		<a href="#my-carousel" class="carousel-control right next" data-slide="next"><h2><i class="glyphicon glyphicon-chevron-right glyphy"></i></h2></a>
	</div>	
</div>
<div class="row col-lg-6 col-md-6 col-xs-12">
	<blockquote class="blockquote-reverse">
	  <h3>"The Earth is ART, the photographer is only a witness."</h3>
	  <footer>Yann Arthus Bertrand  <cite title="Earth From Above">Earth From Above</cite></footer>
	</blockquote>
	<h1>Palmetto Studios</h1>
	<p>Our boutique studio was born out of my unique passion for seeing beauty in everyday life. The majestic works of art that nature provides continued to enthrall me as I grew up and the camera served as my instrument in preserving what my eyes can lovingly behold. Through Palmetto Studios, I offer my humble services honed from years of professionalism from various industries to my clients who have graciously bestowed their trust in our services. Join the growing number of people who have experienced the splendor of memories through our eyes.   <%= link_to 'Contact Palmetto Now!', contact_path%> </p>
</div>

app/views/album/blog.html.erb
<%= provide(:title, "Blog")%>
<div class="content-row top-row">
	<div class="col-xs-12">
		<h2><i class="glyphicon glyphicon-folder-close glyphy"></i> Blog</h2>
	</div>
</div>

app/views/album/clients.html.erb
<%= provide(:title, "Clients")%>
<div class="content-row top-row">
	<div class="col-xs-12">
		<h2><i class="glyphicon glyphicon-briefcase glyphy"></i> Our Clients</h2>
	</div>
</div>

<div class="carousel slide" id="my-carousel">
	  	<ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		    <li data-target="#myCarousel" data-slide-to="3"></li>
		    <li data-target="#myCarousel" data-slide-to="4"></li>
		    <li data-target="#myCarousel" data-slide-to="5"></li>
		    <li data-target="#myCarousel" data-slide-to="6"></li>	    
	  	</ol>
		<div class="carousel-inner">
			<div class="item active">
				<%= image_tag "corporate/corp1.jpg", :class=>"img img-responsive contact-logo" %>
			</div>
			<div class="item">
				<%= image_tag "corporate/corp2.jpg", :class=>"img img-responsive contact-logo" %>
				
			</div>
			<div class="item">
				<%= image_tag "corporate/corp3.jpg", :class=>"img img-responsive contact-logo" %>
				
			</div>
			<div class="item">
				<%= image_tag "7.png", :class=>"img img-responsive contact-logo" %>
				
			</div>
			<div class="item">
				<%= image_tag "corporate/corp4.jpg", :class=>"img img-responsive contact-logo" %>
				
			</div>
			<div class="item">
				<%= image_tag "corporate/corp5.jpg", :class=>"img img-responsive contact-logo" %>
				
			</div>
			<div class="item">
				<%= image_tag "corporate/corp6.jpg", :class=>"img img-responsive contact-logo" %>
				
			</div>
		</div>
		<a href="#my-carousel" class="carousel-control left" data-slide="prev"><h2><i class="glyphicon glyphicon-chevron-left glyphy"></i></a>
		<a href="#my-carousel" class="carousel-control right next" data-slide="next"><h2><i class="glyphicon glyphicon-chevron-right glyphy"></i></h2></a>
</div>

app/views/album/contact.html.erb
<%= provide(:title, "Contact")%>
<div class="content-row top-row">
	<h2><i class="glyphicon glyphicon-pencil glyphy"></i> Contact Palmetto Studios</h2>
	<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
		<div class="sidelogo">
			<%= image_tag "PalmettoLogo.png", :class=>"img img-responsive contact-logo" %>
		</div>
	</div>
	<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
		<ul>
			<li class="contact"><i class="glyphicon glyphicon-home glyphy"></i> 2 Greenwoods Ave, San Andres Pob., Cainta, Philippines </li>
			<li class="contact"><i class="glyphicon glyphicon-phone glyphy"></i> <a href="tel:0011632-500-0222">0011632-500-0222 </li>
			<li class="contact"><i class="glyphicon glyphicon-phone glyphy"></i> <a href="tel:+63 917 874 1222">+63 917 874 1222 </li>
			<li class="contact"><i class="glyphicon glyphicon-envelope glyphy"></i><a href="mailto:palmetto@gmail.com"> palmetto@gmail.com</a></li>		
			<li class="contact"><i class="glyphicon glyphicon-dashboard glyphy"></i> 12PM-9PM Mon-Sat | 2PM-6PM Sun </li>
			<li class="contact"><%=image_tag 'fb.png',:class=>'img'%> <a href="https://www.facebook.com/PalmettoStudios"> Follow us on Facebook! </li>	
		</ul>
	</div>
</div>

app/views/album/home.html.erb
<%= provide(:title, "Home")%>
<div class="row">
	<div class="col-xs-12">
		<h2>Welcome to <div id="home-image"><%=image_tag("PalmettoLogo.png", alt:"Palmetto Studios") %></span></h2>
	</div>
	<div class="carousel slide" id="my-carousel" data-ride="carousel">
	  	<ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		    <li data-target="#myCarousel" data-slide-to="3"></li>
		    <li data-target="#myCarousel" data-slide-to="4"></li>
		    <li data-target="#myCarousel" data-slide-to="5"></li>
		    <li data-target="#myCarousel" data-slide-to="6"></li>	
		    <li data-target="#myCarousel" data-slide-to="7"></li>
		    <li data-target="#myCarousel" data-slide-to="8"></li>	    
	  	</ol>
		<div class="carousel-inner">
			<div class="item active">
				<%= image_tag "1.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Family Portraits</h4></div>
			</div>
			<div class="item">
				<%= image_tag "3.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Family Portraits</h4></div>
			</div>
			<div class="item">
				<%= image_tag "2.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Group Portraits</h4></div>
			</div>

			<div class="item">
				<%= image_tag "4.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Timeless Romance</h4></div>
			</div>
			<div class="item">
				<%= image_tag "5.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Sir Chief and avid fan</h4></div>
			</div>
			<div class="item">
				<%= image_tag "6.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Baby portraits</h4></div>
			</div>
			<div class="item">
				<%= image_tag "8.jpg", :class=>"img img-responsive contact-logo" %>
				<div class="carousel-caption"><h4>Group Photos</h4></div>
			</div>
		</div>
		<a href="#my-carousel" class="carousel-control left" data-slide="prev"><h2><i class="glyphicon glyphicon-chevron-left glyphy"></i></a>
		<a href="#my-carousel" class="carousel-control right next" data-slide="next"><h2><i class="glyphicon glyphicon-chevron-right glyphy"></i></h2></a>		
	</div>
</div>
<div class="services">
	<h1 class="title" id="title-services">Our Services</h1>
	<hr>
	<%= render 'layouts/services' %>
</div>

app/views/layouts/_booking.html.erb
<form action="https://docs.google.com/forms/d/1SmQ6JPhaz5GGZggIstk5MyIGWVbhmOE_TctrIdeVdNw/formResponse" method="POST" id="ss-form" target="_self" onsubmit="">
<ol role="list" class="ss-question-list" style="padding-left: 0">


<div class="ss-form-question errorbox-good" role="listitem">


<div dir="ltr" class="ss-item ss-item-required ss-select">

<div class="ss-form-entry">

<label class="ss-q-item-label" for="entry_1371569665">

<div class="ss-q-title">How did you hear about us?

<label for="itemView.getDomIdToLabel()" aria-label="(Required field)">
</label>


<span class="ss-required-asterisk" aria-hidden="true">*
</span>
</div>


<div class="ss-q-help ss-secondary-text" dir="ltr">
</div>
</label>

<select name="entry.1371569665" id="entry_1371569665" aria-label="How did you hear about us?  " aria-required="true" required="">

<option value=""></option>


<option value="Email">Email</option> 

<option value="Facebook">Facebook</option> 

<option value="Twitter">Twitter</option> 

<option value="Web search">Web search</option> 

<option value="Word of mouth referral">Word of mouth referral</option> 

<option value="Google+">Google+</option>
</select>


<div class="required-message">This is a required question
</div>
</div>
</div>
</div> 

<div class="ss-form-question errorbox-good" role="listitem">


<div dir="ltr" class="ss-item ss-item-required ss-radio">

<div class="ss-form-entry">

<label class="ss-q-item-label" for="entry_171457495">

<div class="ss-q-title">What service are you after?

<label for="itemView.getDomIdToLabel()" aria-label="(Required field)">
</label>


<span class="ss-required-asterisk" aria-hidden="true">*
</span>
</div>


<div class="ss-q-help ss-secondary-text" dir="ltr">
</div>
</label>


<ul class="ss-choices" role="radiogroup" aria-label="What service are you after?  ">
<li class="ss-choice-item">
<label>

<span class="ss-choice-item-control goog-inline-block">
<input type="radio" name="entry.1286918423" value="Video recording" id="group_1286918423_1" role="radio" class="ss-q-radio" aria-label="Video recording" required="" aria-required="true">
</span>


<span class="ss-choice-label">Video recording
</span>

</label></li> 
<li class="ss-choice-item">
<label>

<span class="ss-choice-item-control goog-inline-block">
<input type="radio" name="entry.1286918423" value="Photoshoot" id="group_1286918423_2" role="radio" class="ss-q-radio" aria-label="Photoshoot" required="" aria-required="true">
</span>


<span class="ss-choice-label">Photoshoot
</span>

</label></li> 
<li class="ss-choice-item">
<label>

<span class="ss-choice-item-control goog-inline-block">
<input type="radio" name="entry.1286918423" value="Printing Services" id="group_1286918423_3" role="radio" class="ss-q-radio" aria-label="Printing Services" required="" aria-required="true">
</span>


<span class="ss-choice-label">Printing Services
</span>

</label></li>
</ul>


<div class="error-message" id="171457495_errorMessage">
</div>


<div class="required-message">This is a required question
</div>
</div>
</div>
</div> 

<div class="ss-form-question errorbox-good" role="listitem">


<div dir="ltr" class="ss-item ss-item-required ss-date">

<div class="ss-form-entry">

<label class="ss-q-item-label" for="entry_1395433978">

<div class="ss-q-title">What time do you want to visit our studios?

<label for="itemView.getDomIdToLabel()" aria-label="(Required field)">
</label>


<span class="ss-required-asterisk" aria-hidden="true">*
</span>
</div>


<div class="ss-q-help ss-secondary-text" dir="ltr">Indicate the date and time of your booking.
</div>
</label>

<input type="datetime-local" name="entry.1395433978" value="" class="ss-q-datetime" dir="auto" id="entry_1395433978" aria-label="What time do you want to visit our studios? Indicate the date and time of your booking. " aria-required="true" required="">


<div class="ss-q-time-hint ss-secondary-text">Example: 03/05/2013 11:30 AM
</div>


<div class="required-message">This is a required question
</div>
</div>
</div>
</div> 

<div class="ss-form-question errorbox-good" role="listitem">


<div dir="ltr" class="ss-item ss-item-required ss-text">

<div class="ss-form-entry">

<label class="ss-q-item-label" for="entry_1702004480">

<div class="ss-q-title">Your Email Address

<label for="itemView.getDomIdToLabel()" aria-label="(Required field)">
</label>


<span class="ss-required-asterisk" aria-hidden="true">*
</span>
</div>


<div class="ss-q-help ss-secondary-text" dir="ltr">
</div>
</label>

<input type="text" name="entry.1702004480" value="" class="ss-q-short" id="entry_1702004480" dir="auto" aria-label="Your Email Address  Enter a valid email address" aria-required="true" required="" pattern=".*.*" title="Enter a valid email address">


<div class="error-message" id="174248593_errorMessage">Enter a valid email address
</div>


<div class="required-message">This is a required question
</div>

</div>
</div>
</div> 

<div class="ss-form-question errorbox-good" role="listitem">


<div dir="ltr" class="ss-item ss-item-required ss-text">

<div class="ss-form-entry">

<label class="ss-q-item-label" for="entry_1489513061">

<div class="ss-q-title">Mobile number

<label for="itemView.getDomIdToLabel()" aria-label="(Required field)">
</label>


<span class="ss-required-asterisk" aria-hidden="true">*
</span>
</div>


<div class="ss-q-help ss-secondary-text" dir="ltr">
</div>
</label>

<input type="text" name="entry.1489513061" value="" class="ss-q-short" id="entry_1489513061" dir="auto" aria-label="Mobile number  Must contain " aria-required="true" required="" pattern=".*.*" title="Must contain ">


<div class="error-message" id="1991531595_errorMessage">Must contain 
</div>


<div class="required-message">This is a required question
</div>

</div>
</div>
</div>

<input type="hidden" name="draftResponse" value="[,,&quot;3845913002107525854&quot;]
">

<input type="hidden" name="pageHistory" value="0">



<input type="hidden" name="fbzx" value="3845913002107525854">



<div class="ss-item ss-navigate">
<table id="navigation-table"><tbody>
<tr>
<td class="ss-form-entry goog-inline-block" id="navigation-buttons" dir="ltr">

<input type="submit" name="submit" value="Submit" id="ss-submit" class="jfk-button jfk-button-action ">


<div class="ss-password-warning ss-secondary-text">Never submit passwords through Google Forms.
</div>
</td>

</tr></tbody>
</table>
</div>
</ol>
</form>

app/views/layouts/_button.html.erb
<a href="#menu-toggle" class="rightside" id="menu-toggle"><h1 class="top-row glyphicon glyphicon-align-justify glyphy"></h1></a>

app/views/layouts/_footer.html.erb
<footer class ="navbar-fixed-bottom">
	<nav class="pull-right">
		<ul>
			<li><%= link_to "Home", root_path%></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Clients", clients_path %></li>
			<li><%= link_to "Blog", blog_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a href ="/"><%= image_tag "PalmettoLogo.png", alt: "Palmetto Studios", class:"navbar-brand" %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
             <li><%= link_to " Welcome", root_path %></li>
             <li><%= link_to " About", about_path %></li>
             <li><%= link_to " Clients", clients_path%></li>
             <li><%= link_to " Blog", blog_path %></li>
             <li><%= link_to " Contact", contact_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_services.html.erb
<%#added on June 20, 2015 at 6:57pm%>


<!-- 
<div class="services-content">
	<div class="services col-lg-4 col-md-6 col-xs-12">
		<h1>Photography</h1>
		<%= image_tag'photography.jpg',  class:'services img-thumbnail img img-responsive'%>
		<p>Text goes here</p>
		<%= link_to 'Book Now!', contact_path, class:"btn btn-primary"%>
	</div>
		<div class="services col-lg-4 col-md-6 col-xs-12">
		<h1>Videography</h1>
		<%= image_tag'video.jpg', class:'services img-thumbnail img img-responsive'%>
		<p>Text goes here</p>
		<%= link_to 'Book Now!', contact_path, class:"btn btn-primary"%>
	</div>
	<div class=" services col-lg-4 col-md-6 col-xs-12">
		<h1>Printing Services</h1>
		<%= image_tag'printing.jpg', class:'services img-thumbnail img img-responsive'%>
		<p>Text goes here</p>
		<%= link_to 'Book Now!', contact_path, class:"btn btn-primary"%>
	</div>
</div> -->


<div class="row">
	<div class="col-xs-12 col-md-4">
		<div class="services-block">
			<div class="service-summary">
				<h3>Photography</h3>
			</div>
			<div class="services-body">
				<%= image_tag'photography.jpg',  class:'img img-responsive'%>
			</div>
			<div class="services-footer">
				<h4><%= link_to '<span class="glyphicon glyphicon-chevron-right
                pull-right"></span>Contact Us'.html_safe, contact_path %> </h4>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-md-4">
		<div class="services-block">
			<div class="service-summary">
				<h3>Videography</h3>
			</div>
			<div class="services-body">
				<%= image_tag'video.jpg',  class:'img img-responsive'%>
			</div>
			<div class="services-footer">
				<h4><%= link_to '<span class="glyphicon glyphicon-chevron-right
                pull-right"></span>Contact Us'.html_safe, contact_path %> </h4>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-md-4">
		<div class="services-block">
			<div class="service-summary">
				<h3>Printing Services</h3>
			</div>
			<div class="services-body">
				<%= image_tag'printing.jpg',  class:'img img-responsive'%>
			</div>
			<div class="services-footer">
				<h4><%= link_to '<span class="glyphicon glyphicon-chevron-right
                pull-right"></span>Contact Us'.html_safe, contact_path %> </h4>
			</div>
		</div>
	</div>

</div>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <div class="content-row=aside">
        <li id="sidebar-brand">
           <a href ="/"><%= image_tag "PalmettoLogo.png", class:"img img-responsive size-logo" %></a>
        </li>
        <li><strong><i class="glyphicon glyphicon-home glyphy"></i><%= link_to " Welcome", root_path, class:"sidemenu" %></strong></li>
        <li><strong><i class="glyphicon glyphicon-camera glyphy"></i><%= link_to " About", about_path, class:"sidemenu" %></strong></li>
         <li><strong><i class="glyphicon glyphicon-briefcase glyphy"></i><%= link_to " Clients", clients_path%></strong></li>
         <li><strong><i class="glyphicon glyphicon-folder-close glyphy"></i><%= link_to " Blog", blog_path %></strong></li>
        <li><strong><i class="glyphicon glyphicon-pencil glyphy"></i><%= link_to " Contact", contact_path %></li>
    </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
   <div id="container">
		<%= render 'layouts/navbar'%>
        <!-- Page Content -->
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <%= render 'layouts/button' %>
                    </div>
                    <div class="col-xs-12">
                        <%= yield %>
                    </div>
                    <div class="col-xs-12">
                        <%= render 'layouts/footer'%>
                    </div>
                </div>
            </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
</body>
</html>